### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
- Update `sentry` to newest version available
 - Update project and example to Android 12

### CODE REVIEW

**Comment by MOPineyro** [comment]
Hey would like this update merged in, having some issues with sentry right now that I believe this resolves

**Comment by ThexXTURBOXx** [comment]
You can already use my fork via e.g. In the `dependecy_overrides` as a `git` type dependency :)

**Comment by ThexXTURBOXx** [comment]
@jhomlala Some projects of mine require this change. Any chance this gets merged soon? :)

**Comment by alr2413** [comment]
Ping @jhomlala .
Please merge it thanks.

**Comment by jhomlala** [comment]
LGTM, thanks!

**Pull request merged**
