### PR TITLE
Some library and flutter version updates.

### PR DESCRIPTION
**Pull request by JhonaCodes**
## 0.7.1
* [BREAKING_CHANGE] Update to Flutter 3.10.5 by Jhonacode (https://github.com/JhonaCodes)
* [BREAKING_CHANGE] Update some library's by Jhonacode (https://github.com/JhonaCodes)
* Change ``with ReportModeAction`` to ```implements ReportModeAction```, now its abstract class.
* Change values for ``sendTimeout and receiveTimeout`` to ```Duration()```

### CODE REVIEW

**Comment by calcitem** [comment]
Changing the version of flutter_mailer to ^2.0.4 still cannot solve the problem of catcher compilation failure, see https://github.com/taljacobson/flutter_mailer/issues/55#issuecomment-1605788713, this problem needs to be corrected by the upstream package developer  OK, otherwise the catcher needs to modify the dependency to remove the ^ symbol and lock it at 2.0.4.

**Comment by JhonaCodes** [comment]
> Changing the version of flutter_mailer to ^2.0.4 still cannot solve the problem of catcher compilation failure, see [taljacobson/flutter_mailer#55 (comment)](https://github.com/taljacobson/flutter_mailer/issues/55#issuecomment-1605788713), this problem needs to be corrected by the upstream package developer OK, otherwise the catcher needs to modify the dependency to remove the ^ symbol and lock it at 2.0.4.

Thanks for your reply, I made some changes to the library example, so it should now work without problems.
Screenshot 2023-06-26 at 12 12 21 PM

Screenshot 2023-06-26 at 12 12 10 PM
Screenshot 2023-06-26 at 12 14 17 PM

**Comment by calcitem** [comment]
This build problem will only be exposed when the upgrade operation is performed, or when the package cache is deleted and rebuilt. If you do not encounter problems, it may be because there is no upgrade package, but this way of writing will cause automatic upgrades. It is recommended to remove the ^ symbol.

**Comment by calcitem** [comment]
In addition, if you set the min sdk version of your android app to 21 or higher, it will not expose the problem.

**Pull request closed without merging**
