### PR TITLE
Android Lifecycle

### PR DESCRIPTION
**Pull request by dlanileonardo**
- Use Android Lifecycle [flutter_plugin_android_lifecycle](https://pub.dev/packages/flutter_plugin_android_lifecycle)
- Pass ErrorDetails for Report, to use in CustomErrorHandler (Ex. CrashlyticsHandler)

### CODE REVIEW

**Comment by ThiagoAnunciacao** [comment]
👍

**Comment by jhomlala** [comment]
Thank you for your PR @dlanileonardo.
Please explain why do you want to introduce these changes?

**Comment by dlanileonardo** [comment]
@jhomlala you welcome! 😃 

**flutter_plugin_android_lifecycle**

- The New API is better, maximize compatibility with other embedding plugins. 
  - [Plugins that were migrated](https://github.com/flutter/plugins/pull/2299)
  - [Guide to Migrate](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration)
- I can't reproduce errors in my environment (because I have not android device in this moment), but in old versions of Flutter, catcher with another embedded plugins you receive this error on release run: ```java.lang.RuntimeException: Unable to start activity```

**ErrorsDetails in Handler**

- I use Crashlytics with Catcher to log errors, and Crashlytics you can pass raw _FlutterErrorDetails_ instance an argument.
```Crashlytics.instance.recordFlutterError(error.errorDetails);```

**Comment by jhomlala** [comment]
Thanks, merged.

**Pull request merged**
