### PR TITLE
Add basic desktop  support for macOS/Windows

### PR DESCRIPTION
**Pull request by narumishi**
Currently, `catcher` package only support Android, iOS and web. However, most functions should be compatible for desktop and easy to implement. 

**Compatible handlers:**
- `ConsoleHandler`: it only depends on `logging` which is a pure dart package and `catcher` handle message by `print` only. **Even it should support** `PlatformType.Unknown`.
- `FileHandler`: `io` module should support all desktops.
- `HttpHandler`, `SentryHandler`, `SlackHandler`, `DiscardHandler`, `EmailAutoHandler`:
    - these depend on `dio` and `mailer`, which also support http connections for desktops. 

For above changes, it should also be compatible with Linux, but I don't have a flutter-linux environment to test. But it should be supported. If you could test linux, please add linux support later.

**Compatible report modes:**
- currently, all report modes are pure material/cupertino widgets. **Even it should support** `PlatformType.Unknown`.

**Incompatible:**
- `EmailManualHandler`: `flutter_mailer` doesn't support desktop yet. Alternative solution not found.
- `ToastHandler`: `fluttertoast` doesn't support desktop. Other alternative like `flutter_easyloding`, `bot_toast` are support all platforms since they are pure flutter packages.
- `device_info`: only support android and ios, so let's skip it if it's not supported. (It was using `if android else ios`, which will raise error in desktop)
- `package info`: only android, ios and macOS. It's better to check **is some platform** rather **is not some platform**

### CODE REVIEW

**Comment by jhomlala** [comment]
Support for platforms was added in different PR. Anyway thanks for contribution!

**Comment by narumishi** [comment]
@jhomlala thanks. And there are still some issues using 0.6.1:
1. build failed in windows because of catcher doesn't contain `CMakeLists.txt`, add it with default content under `windows/`will solve it. 
```
cmake_minimum_required(VERSION 3.10)
set(PROJECT_NAME "catcher")
project(${PROJECT_NAME} LANGUAGES CXX)

set(PLUGIN_NAME "${PROJECT_NAME}_plugin")

add_library(${PLUGIN_NAME} SHARED
  "${PLUGIN_NAME}.cpp"
)
apply_standard_settings(${PLUGIN_NAME})
set_target_properties(${PLUGIN_NAME} PROPERTIES
  CXX_VISIBILITY_PRESET hidden)
target_compile_definitions(${PLUGIN_NAME} PRIVATE FLUTTER_PLUGIN_IMPL)
target_compile_definitions(${PLUGIN_NAME} PRIVATE _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING)
target_include_directories(${PLUGIN_NAME} INTERFACE
  "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_link_libraries(${PLUGIN_NAME} PRIVATE flutter flutter_wrapper_plugin)

# List of absolute paths to libraries that should be bundled with the plugin
set(file_chooser_bundled_libraries
  ""
  PARENT_SCOPE
)
```
2.  inside `_loadApplicationInfo`, still use `not web` to determine whether load PackageInfo, but this package doesn't support linux and windows now.
https://github.com/jhomlala/catcher/blob/58dadb67daeebdfe1372cdd9df14e6e68086c5f9/lib/core/catcher.dart#L363-L370
I think it is better to use `isAndroid&&isIOS&&isMacOS` to enable PackageInfo resolving?  Or using `package_info_plus` to support all platforms?

**Comment by LiveRock** [comment]
EmailAutoHandler can't work in macOS.
Always return 

```
535 Incorrect authentication data
Catcher | WARNING] Instance of 'EmailAutoHandler' failed to report error
```

**Comment by narumishi** [comment]
@LiveRock I guess you didn't configure your mail server correctly, like not enable the STMP service? Make sure you can send mail in other platform first. 
Anyway, it's the issue with `mailer` plugin.

**Pull request closed without merging**
